[2024-01-31 13:30:37,194] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_3.create_table manual__2024-01-31T13:30:28.720660+00:00 [queued]>
[2024-01-31 13:30:37,279] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_3.create_table manual__2024-01-31T13:30:28.720660+00:00 [queued]>
[2024-01-31 13:30:37,280] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 13:30:37,280] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-01-31 13:30:37,281] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 13:30:37,374] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): create_table> on 2024-01-31 13:30:28.720660+00:00
[2024-01-31 13:30:37,446] {standard_task_runner.py:52} INFO - Started process 3606 to run task
[2024-01-31 13:30:37,461] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'project_6_3', 'create_table', 'manual__2024-01-31T13:30:28.720660+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpr4czefsf', '--error-file', '/tmp/tmpaksakp3m']
[2024-01-31 13:30:37,465] {standard_task_runner.py:80} INFO - Job 71: Subtask create_table
[2024-01-31 13:30:38,089] {task_command.py:369} INFO - Running <TaskInstance: project_6_3.create_table manual__2024-01-31T13:30:28.720660+00:00 [running]> on host 8ebb6ccf62d7
[2024-01-31 13:30:39,240] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_6_3
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-01-31T13:30:28.720660+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-31T13:30:28.720660+00:00
[2024-01-31 13:30:39,247] {mysql.py:82} INFO - Executing: 
                create table if not exists test_1 (
                dt date,
                dag_id character varying
                )
        
[2024-01-31 13:30:39,415] {base.py:68} INFO - Using connection ID 'mysql_data_staging' for task execution.
[2024-01-31 13:30:39,660] {dbapi.py:208} INFO - Running statement: 
                create table if not exists test_1 (
                dt date,
                dag_id character varying
                )
        , parameters: None
[2024-01-31 13:30:39,671] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/operators/mysql.py", line 84, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 188, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 212, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 4")
[2024-01-31 13:30:39,836] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=project_6_3, task_id=create_table, execution_date=20240131T133028, start_date=20240131T133037, end_date=20240131T133039
[2024-01-31 13:30:39,972] {standard_task_runner.py:97} ERROR - Failed to execute job 71 for task create_table ((1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 4"); 3606)
[2024-01-31 13:30:40,024] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-31 13:30:40,555] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
