[2024-01-31 13:50:49,129] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_5.create_table scheduled__2024-01-30T13:50:14.776191+00:00 [queued]>
[2024-01-31 13:50:49,156] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_5.create_table scheduled__2024-01-30T13:50:14.776191+00:00 [queued]>
[2024-01-31 13:50:49,156] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 13:50:49,156] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2024-01-31 13:50:49,157] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 13:50:49,231] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): create_table> on 2024-01-30 13:50:14.776191+00:00
[2024-01-31 13:50:49,260] {standard_task_runner.py:52} INFO - Started process 4335 to run task
[2024-01-31 13:50:49,269] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'project_6_5', 'create_table', 'scheduled__2024-01-30T13:50:14.776191+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpsz3ke62o', '--error-file', '/tmp/tmp6n9yx_wt']
[2024-01-31 13:50:49,271] {standard_task_runner.py:80} INFO - Job 91: Subtask create_table
[2024-01-31 13:50:49,617] {task_command.py:369} INFO - Running <TaskInstance: project_6_5.create_table scheduled__2024-01-30T13:50:14.776191+00:00 [running]> on host 8ebb6ccf62d7
[2024-01-31 13:50:50,022] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_6_5
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-01-30T13:50:14.776191+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-30T13:50:14.776191+00:00
[2024-01-31 13:50:50,024] {mysql.py:82} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS test_1 (
                dt DATE,
                dag_id VARCHAR(255)
            )
        
[2024-01-31 13:50:50,108] {base.py:68} INFO - Using connection ID 'mysql_data_staging' for task execution.
[2024-01-31 13:50:50,238] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS test_1 (
                dt DATE,
                dag_id VARCHAR(255)
            )
        , parameters: None
[2024-01-31 13:50:50,242] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/operators/mysql.py", line 84, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 188, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 212, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1046, 'No database selected')
[2024-01-31 13:50:50,349] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=project_6_5, task_id=create_table, execution_date=20240130T135014, start_date=20240131T135049, end_date=20240131T135050
[2024-01-31 13:50:50,402] {standard_task_runner.py:97} ERROR - Failed to execute job 91 for task create_table ((1046, 'No database selected'); 4335)
[2024-01-31 13:50:50,452] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-31 13:50:50,688] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
