[2024-01-31 13:28:59,288] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_2.create_table manual__2024-01-31T13:28:36.735960+00:00 [queued]>
[2024-01-31 13:28:59,315] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_2.create_table manual__2024-01-31T13:28:36.735960+00:00 [queued]>
[2024-01-31 13:28:59,315] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 13:28:59,316] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2024-01-31 13:28:59,316] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 13:28:59,353] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): create_table> on 2024-01-31 13:28:36.735960+00:00
[2024-01-31 13:28:59,365] {standard_task_runner.py:52} INFO - Started process 3523 to run task
[2024-01-31 13:28:59,370] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'project_6_2', 'create_table', 'manual__2024-01-31T13:28:36.735960+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmps6p3m0_5', '--error-file', '/tmp/tmp_08krtgm']
[2024-01-31 13:28:59,371] {standard_task_runner.py:80} INFO - Job 67: Subtask create_table
[2024-01-31 13:28:59,681] {task_command.py:369} INFO - Running <TaskInstance: project_6_2.create_table manual__2024-01-31T13:28:36.735960+00:00 [running]> on host 8ebb6ccf62d7
[2024-01-31 13:29:00,049] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_6_2
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-01-31T13:28:36.735960+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-31T13:28:36.735960+00:00
[2024-01-31 13:29:00,051] {mysql.py:82} INFO - Executing: 
                create table if not exist test_1 (
                dt date,
                dag_id character varying
                )
        
[2024-01-31 13:29:00,148] {base.py:68} INFO - Using connection ID 'mysql_data_staging' for task execution.
[2024-01-31 13:29:00,292] {dbapi.py:208} INFO - Running statement: 
                create table if not exist test_1 (
                dt date,
                dag_id character varying
                )
        , parameters: None
[2024-01-31 13:29:00,296] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/operators/mysql.py", line 84, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 188, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 212, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'exist test_1 (\n                dt date,\n                dag_id character varying' at line 1")
[2024-01-31 13:29:00,392] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=project_6_2, task_id=create_table, execution_date=20240131T132836, start_date=20240131T132859, end_date=20240131T132900
[2024-01-31 13:29:00,440] {standard_task_runner.py:97} ERROR - Failed to execute job 67 for task create_table ((1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'exist test_1 (\n                dt date,\n                dag_id character varying' at line 1"); 3523)
[2024-01-31 13:29:00,477] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-31 13:29:00,744] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
